### ISSUE TITLE
Server side collision detection.

### ISSUE THREAD

**Issue by leikjatru** [kirkja-leikjahonnunar/kor#1]
# Questions
- Why is the player movement lagging on the GameServer?
- Should we be using move_and_slide() on the GameServer?
- Where should we place the GameClient update code once it receives the world state from the GameServer?

# Goal
Prevent the GameClient from feeding bogus position data to the GameServer.

# Tests
- [x] Remove the Player's collision ability from the Client.
- [x] Add colliders to the Player class on the Server.
- [ ]  Check the Player collision on the Server then send the "official" position back to the Client.
- [ ] **Server-side view:** Accept the user input `rpc_id()` calls. Use `move_and_slide()` to calculate the player positions (20 times / sec.) .
- [ ] **Client-side:** Receive input from the user. Send the position to the Server (60 times / sec.) .

**Comment by tomlechner** [comment]
Deferring for now.
