### ISSUE TITLE
General 3D Modeling Workflow

### ISSUE THREAD

**Issue by unblinky** [kirkja-leikjahonnunar/kor#14]
# Issues
- [ ] **Hi to Lo AO Bug:** Can't seem to grab the AO data from just the `Sculpt`. It keeps rendering the intersection of the `Lo Poly` and `Hi Poly` models.
- [ ] How far can we push Blender? Can we _reasonably_ model, sculpt, and paint all in one yet?

# What should our open source modeling workflow be?
- Box Modeling: Model > UV > Texture.
- Hi Poly Sculpts: Vert Model + Skin Modifier > Sculpt. (color paint?)
- Lo Poly Retopo: Snap Model > UV > Texture Bake > Texture Paint.
- Texturing: Stitch > Touch Up > Export.

## Deliverables
Static mesh and associated textures.

## Reference
When modeling a new `game object`, we start by gathering reference. What makes this thing believable in the world we wish to build?

Reference can be **any type of media that communicates the _next steps_ we need to proceed**:
- Text Descriptions
- Image Search
- Concept Art
- Photos
- Maquettes
- Drawings on napkins.
- Whiteboards
- Lego Bricks
- A cut up paper bag with stickers.
- Any; or all of the above!

Store any reference images into a [PrueRef](https://www.pureref.com/download.php) file in the `game object`'s folder. PurRef is an awesome reference image layout application that streamlines the image gathering and sorting process for digital artists of any kind. _(not sponsored)_. The app may be used for free, but please consider supporting the developers of this wonderful tool - https://www.pureref.com/download.php

# Blender
- https://blender.org/download
- https://github.com/nutti/Screencast-Keys/releases

### Modifiers
- Mirror
- Smooth

#### `Edit Mode`
  - Vertex select: **`[1]`**
  - Edge select: **`[2]`**
  - Face select: **`[3]`**
- Extrude: **`[E]`**
- Loop Cut: **`[Ctrl]` + `[R]`**

## Vert Model
![image](https://user-images.githubusercontent.com/47279470/169632648-8f7715b6-1518-4e91-a6b7-bfc87df557c5.png)

### Modifiers
- **`Mirror`**
  - On Cage: **`🗹`**
  - Clipping: **`🗹`**
  - Merge: `0.1 m`
- **`Skin`**
  - Smooth Shading: **`🗹`** _(only visible in `Object Mode`)_
  - Mark "pelvis" vertex as root: `[Mark Root]`
- **`Subdivision Surface`**
  - Levels Viewport: `2`

### Hotkeys
- `Edit Mode` > `Vertex Selection` > Scale vertex radius: **`[Ctrl]` + `[A]`**

#### `Sculpt Mode`
- Build out: **`[LMB]` drag**.
- Push in: **`[Ctrl]` + `[LMB]` drag**
- Smooth: **`[Shift]` + `[LMB]` drag**
- Size Brush: **`[F]`**

### Modifiers
- **`Mirror`**
  - Clipping: **`🗹`** _(as needed)_
- **`Shrink Wrap`**
  - Target: `Sculpt Object`

### Hotkeys
- `Edit Mode` > `Vertex Selection` or > Extrude to mouse click _(vert & edge)_: **`[Ctrl]` + `[RMB]`**

## Bake Hi Poly to Lo Poly
- `Render Properties` tab
  - Render Engine: `Cycles`
  - `Bake`
    - Bake Type: `Normal` or `Ambient Occlusion`
    - Selected to Active: **`🗹`**

### Normal Map
Don't forget to set the normal map node's **Color Space:** `Non-Color`
![Image](https://user-images.githubusercontent.com/47279470/171889772-4a4fb424-c8e2-4bda-ac64-f57bd23df6df.png)
Solution: https://blender.stackexchange.com/questions/211934/normal-map-creates-seams

**Comment by lillymjames** [comment]
hello!
