### ISSUE TITLE
Character Controller

### ISSUE THREAD

**Issue by leikjatru** [kirkja-leikjahonnunar/kor#3]
# Move for fun!
### Inhabitable Class
Modular nodes with scripts. Scene tab nodes.

### Third Person Character Controller

- [x] Wall and floor collision.
- [ ] Angle slides and friction.
- [x] Jump.
- [x] Gravity.
- [x] Leaning.
- [x] Triggers.
- [ ] Moving platforms
- [ ] Laser pointer and decals.
- [ ] Network sync.

**Comment by tomlechner** [comment]
Transferring issue to new repo.
